name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR and DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: |
          # Build the Docker image
          rev=$(git rev-parse --short HEAD)
          docker build -t anma061/testern .

          # Tag the image for AWS ECR
          docker tag anma061/testern:latest 244530008913.dkr.ecr.eu-west-1.amazonaws.com/anma061/testern:latest

          # Tag the image for DockerHub
          docker tag anma061/testern:latest dockern69/dockertestanma:latest

      - name: Push to AWS ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Login to AWS ECR and push the image
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/anma061/testern:latest

      - name: Push to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
        run: |
          # Login to DockerHub and push the image
          echo "${DOCKER_SECRET}" | docker login -u "dockern69" --password-stdin
          docker tag anma061/testern dockern69/dockertestanma
          docker push dockern69/dockertestanma:latest
